[이아영] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-1-team pull request #14
Opened 2021-12-21 06:47 UTC by leeay3

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
- urls.py 수정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- urls import 형식 수정
- 이메일, 패스워드로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:02 UTC, Kang-kyunghun requested changes

2021-12-21 07:02 UTC, Kang-kyunghun commented on students/ahyounglee/users/views.py
> +                raise ValidationError('INVALID_USER')
email하고 password가 동시에 만족하는 유저를 찾아야 하므로 다음과 같이 수정하면 좋을 것 같습니다.
```suggestion
            if not User.objects.filter(email=email, password=password).exists():
                raise ValidationError('INVALID_USER')
```

2021-12-21 07:02 UTC, Kang-kyunghun commented on students/ahyounglee/users/views.py
> +                raise ValidationError('INVALID_USER')
```suggestion
```

2021-12-21 07:24 UTC, leeay3 commented on students/ahyounglee/users/views.py
> +                raise ValidationError('INVALID_USER')
수정완료했습니다!

2021-12-21 07:24 UTC, leeay3 commented on students/ahyounglee/users/views.py
> +                raise ValidationError('INVALID_USER')
수정 완료했습니다!

2021-12-21 09:54 UTC, Kang-kyunghun requested changes

2021-12-21 09:54 UTC, Kang-kyunghun commented on students/ahyounglee/users/views.py
> +            if not is_email_valid(email, password):
여기에 password를 추가한 이유가 있을까요?
이렇게 되면 함수가 동작 안 할 것 같고, 함수의 목적에도 안 맞을 것 같습니다.

2021-12-23 01:42 UTC, leeay3 commented on students/ahyounglee/users/views.py
> +            if not is_email_valid(email, password):
잘못 입력하고 삭제를 못했습니다. 수정 완료 했습니다.

2021-12-23 02:09 UTC, Kang-kyunghun commented
LGTM~!

2021-12-23 02:09 UTC, merged