[김홍주] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-1-team pull request #15
Opened 2021-12-21 06:51 UTC by hjk0795

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일, 패스워드 validation 검사 기능

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:08 UTC, kyeongraekim requested changes
아래내용 확인하여 수정해주세요!~

2021-12-21 07:08 UTC, kyeongraekim commented on students/hongju/users/urls.py
> +        path('signUp', SignUpView.as_view())
url은 RESTful API에 입각한 컨벤션에 따라 대문자가아닌 소문자로 작성해주세요.

2021-12-21 07:08 UTC, kyeongraekim commented on students/hongju/users/views.py
> +# 빈 데이터입력 확인
코드를 읽어서 이해가 되는 부분에는 불필요한 주석을 따로 달 필요가 없습니다 참고해주세요!~

2021-12-21 07:08 UTC, kyeongraekim commented on students/hongju/users/views.py
> +def validate_email(email_data):
해당 내용은 동일 view 파일에 작성하는 것보다 모듈화로 따로 빼서 작성해보세요!~

2021-12-21 07:08 UTC, kyeongraekim commented on students/hongju/users/views.py
> +        isValidEmail = validate_email(data['email'])
파이썬 컨벤션상 변수명은 CamelCase가 아닌 snake_case 로 작성해주세요!~

2021-12-21 07:08 UTC, kyeongraekim commented on students/hongju/users/views.py
> +        except:
except만 사용해서 Error를 핸들링 하는 경우는 피해야 합니다. 그 이유는 파이썬에 발생시키는 모든 에러에 대해서 except문으로 빠지게 됩니다. 이런 구조로 코드를 작성한다면 당연히 디버깅 하기가 어려워 지겠죠?

(디버깅 : 나중에 기능에 버그가 생겼을 경우에 어디서 문제가 생겼는지 찾기가 어려움)

```python
try:
    ..
except:
    ..
```

결론적으로 `try, except`문을 사용해서 error를 핸들링하는 경우 아래와 같이 에러를 명확하게 잡아주셔야 합니다.

```python
try:

except KeyError:
    return ..    
```

2021-12-21 07:34 UTC, hjk0795 commented
수정했습니다.

2021-12-21 07:53 UTC, kyeongraekim requested changes
아래 수정사항 확인해주세요!~

2021-12-21 07:53 UTC, kyeongraekim commented on students/hongju/users/views.py
> +from users.validation import *
import * 사용은 추후에 혼선을 불러 올 수 있으니 지양하는 습관을 들이는게 좋습니다~ 정말 다량의 함수와 클래스 등을 임포트 할 때를 제외하면은 원하는 validation 함수 명을 직접 호출하는 방향으로 작성해주세요~

2021-12-21 07:53 UTC, kyeongraekim commented on students/hongju/users/views.py
> +            if is_valid_pw == 'no_match':
변수명은 최대한 영어 원어 그대로를 풀어서 써주세요!~ pw보다 password 등의 어휘선택을 지향해주셔야합니다~

2021-12-21 07:53 UTC, kyeongraekim commented on students/hongju/users/validation.py
> +    return True
아래와 같이 불필요한 문자열을 반환값으로 리턴하는 것보다 에러를 바로 raise 하는 것이 좋은 방향일 수 있습니다. 전반적인 validation.py 내용 수정을 고려해보세요!~ 훨씬 코드가 가독성이 좋아질 것으로 보입니다.

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_PASSWORD')
```

2021-12-21 08:27 UTC, hjk0795 commented
수정했습니다.

2021-12-21 10:20 UTC, Kang-kyunghun requested changes

2021-12-21 10:20 UTC, Kang-kyunghun commented on students/hongju/users/views.py
> +                )
```suggestion
            User.objects.create(
                name         = data['name'],
                email        = data['email'],
                password     = data['password'],
                phone_number = data['phone_number'],
            )
```

2021-12-21 10:20 UTC, Kang-kyunghun commented on students/hongju/westagram/urls.py
> +        path('user/', include('users.urls'))
```suggestion
        path('user', include('users.urls'))
```

2021-12-21 10:20 UTC, Kang-kyunghun commented on students/hongju/users/urls.py
> +        path('signup', SignUpView.as_view())
```suggestion
        path('/signup', SignUpView.as_view())
```

2021-12-22 08:55 UTC, hjk0795 commented
수정했습니다.

2021-12-22 09:25 UTC, kyeongraekim approved these changes
LGTM!~

2021-12-22 09:26 UTC, merged