[장민욱] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-1-team pull request #17
Opened 2021-12-21 11:52 UTC by black2code

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 계정, 비밀번호 일치 여부 확인 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 12:13 UTC, Kang-kyunghun requested changes

2021-12-21 12:13 UTC, Kang-kyunghun commented on students/minwookjang/users/views.py
> +
굳이 함수로 빼지 않아도 될 것 같습니다.
반복적으로 사용하는 코드도 아니고, 오히려 함수로 빼서 가독성을 떨어뜨리고 있습니다.

2021-12-21 12:13 UTC, Kang-kyunghun commented on students/minwookjang/users/views.py
> +            login_password_check(data['email'],data['password'])
email 확인은 없어도 될 것 같습니다.
결국 목적은 input으로 들어온 email과 password를 동시에 만족하는 데이터가 DB에 존재하는지를 판단하면 되기 때문입니다.

2021-12-21 12:22 UTC, black2code commented
수정 완료했습니다.

2021-12-22 01:23 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-22 01:23 UTC, merged