[장민욱] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-1-team pull request #8
Opened 2021-12-17 08:27 UTC by black2code

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- User 테이블 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 컬럼 생성 : 이름, 이메일, 패스워드, 핸드폰번호, 생년월일, 생성날짜, 수정날짜
- 핸드폰 번호는 정규식을 이용하여
ex. 010-1234-5678, 01012345678 형식으로 작성하도록 함

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 09:51 UTC, kyeongraekim requested changes
민욱님 아래  내용 확인해서 수정해주세요!~

2021-12-17 09:51 UTC, kyeongraekim commented on students/minwookjang/users/models.py
> +    phone_number_regex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
정규표현식은 Client와 보다 더 가까운 View단에서 실행시켜 주시는게 더 효율적입니다. 해당 내용은 삭제해주세요!~

2021-12-17 09:51 UTC, kyeongraekim commented on students/minwookjang/users/models.py
> +    date_of_birth      = models.DateField()
인스타그램시 생년월일이 꼭 기입이 되어야 할까요? 선택 정보이면 null=True 속성을 추가하는 것을 고려해보세요!~

2021-12-17 09:51 UTC, kyeongraekim commented on students/minwookjang/users/models.py
> +    phone_number       = models.CharField(validators = [phone_number_regex], max_length = 11, unique = True)
위 내용이 바뀐다면 해당 내용도 불필요한 부분은 삭제하면 좋을 것 같네요!

2021-12-17 12:50 UTC, black2code commented
말씀하신 사항 수정 완료했습니다.

2021-12-18 01:31 UTC, Kang-kyunghun commented
LGTM~~!!

2021-12-18 01:31 UTC, merged