[이아영] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-1-team pull request #9
Opened 2021-12-17 08:32 UTC by leeay3

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user app 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- user app 생성
- user table 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- models.py에서 user의 name을 username으로 해야하나요 name으로 해야하나요? 멘토님들 의견이 다르셔서 여쭤봅니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-18 01:30 UTC, Kang-kyunghun requested changes

2021-12-18 01:30 UTC, Kang-kyunghun commented on students/ahyounglee/users/models.py
> +    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
```suggestion
    password         = models.CharField(max_length=256, blank=False, null=False)
```

1. python에서 변수명은 카멜 케이스로 만들어야 합니다.
2. model의 class에서는 field 선언에 관련된 것만 넣어 주세요. validation과 관련된 로직은 view에서 처리하면 됩니다.
3. phone의 validators 속성도 제거해 주세요.

2021-12-18 01:30 UTC, Kang-kyunghun commented on students/ahyounglee/users/models.py
> +
불필요한 공백은 제거해 주세요.

2021-12-19 04:57 UTC, leeay3 commented on students/ahyounglee/users/models.py
> +    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
수정했습니다.
확인 부탁드립니다.

2021-12-19 04:57 UTC, leeay3 commented on students/ahyounglee/users/models.py
> +
수정했습니다.
확인 부탁드립니다.

2021-12-19 23:53 UTC, Kang-kyunghun requested changes

2021-12-19 23:53 UTC, Kang-kyunghun commented on students/ahyounglee/users/models.py
> +    phone            = models.CharField(max_length = 11, unique = True)
1. blank 속성을 언제 사용해야 하는지 코멘트로 남겨주세요.(blank=False도 기본 옵션이기 때문에 제거해 주세요.)
2. null=False는 기본 설정이기 때문에 안 적으셔도 됩니다. 제거해 주세요.
3. phone -> phone_number가 더 명확할 것 같고, max_length도 조금 더 여유롭게 40~50정도로 잡아주세요.

2021-12-19 23:53 UTC, Kang-kyunghun commented on students/ahyounglee/users/models.py
> +class User(models.Model):
사용하지 않는 모듈은 제거해 주시고, class와의 간격은 1줄로 해주세요.
```suggestion
from django.db import models

class User(models.Model):
```

2021-12-20 03:54 UTC, leeay3 commented on students/ahyounglee/users/models.py
> +class User(models.Model):
수정했습니다.

2021-12-20 03:56 UTC, leeay3 commented on students/ahyounglee/users/models.py
> +    phone            = models.CharField(max_length = 11, unique = True)
blank 속성은 필드가 폼에서 빈 채로 저장되는 것 / null은 필드의 값이 NULL(정보 없음)로 저장되는 것입니다.
다른 수정내용은 수정 완료했습니다.

2021-12-20 05:07 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-20 05:07 UTC, merged

2021-12-20 05:14 UTC, Kang-kyunghun commented on students/ahyounglee/users/models.py
> +    phone            = models.CharField(max_length = 11, unique = True)
blank는 django의 form을 사용해야지만 의미가 있는 속성이므로 저희는 사용하지 않는 옵션이에요. 그래서 null 속성이나, default 속성을 사용하시면 됩니다.